# Required for the web tracker
mysql:
  enabled: false
  ip: "panel.seailz.com"
  port: "3306"
  name: "a_good_old_database"
  password: "seailz"
  username: "not_seailz"

game:
  lives: 3
  tower-claim-time: 7 # Time (in seconds) that it takes to claim a tower

use118: true
# Whether the minigame should use the 1.18 world creation method.