name: SpigotPluginTemplate
version: ${project.version}
main: com.seailz.spigotplugintemplate.SpigotPluginTemplate
api-version: 1.18
authors: [ Seailz ]
description: Plugin Tempalte (Change this!)
website: www.seailzcom
